Updates: Add mechanism to update boot and blfs partitions (#208)
The FIT is installed on the boot partition on all targets, along with
some other files.

In the MBL Raspberry PI 3 image we also have a 'bootloader FS' (BLFS)
partition, which holds armstub8.bin. armstub8.bin contains BL2.

When both the 'boot' and BLFS partitions exist, they actually
contain exactly the same files: MBL's wic image creation code installs the
same files to both partitions.

So add code to arm_update_activate.sh to handle copying files to the boot
and BLFS partitions (if the BLFS partition exists).

This enables the FIT update on all platforms and the BL2 update on
Raspberry PI 3.

arm_update_activate expects the files in the update payload to be
named with the name of the partition they're being copied to.
If we're updating one of the boot or BLFS partitions, the files to
update will be in a directory named with the partition name.
We also check if the BLFS partition exists, and if it does, the file(s)
are copied to both partitions. If BLFS does not exist, or is marked
as 'skipped', the files are only copied to the boot partition.

JIRA: IOTMBL-2405, IOTMBL-2284

diff --git a/cloud-services/mbl-cloud-client/scripts/arm_update_common.sh.in b/cloud-services/mbl-cloud-client/scripts/arm_update_common.sh.in
--- a/cloud-services/mbl-cloud-client/scripts/arm_update_common.sh.in
+++ b/cloud-services/mbl-cloud-client/scripts/arm_update_common.sh.in
@@ -138,3 +138,18 @@ emodFsType="$3"
 get_active_root_device() {
     lsblk -nrpo NAME,MOUNTPOINT | grep -e ".* /$" | cut -d ' ' -f1
 }
+
+# Remount a partition.
+# Exits on errors.
+#
+# $1: Mount point of the target partition
+# $2: Mount options e.g rw or ro
+remount_partition_or_die() {
+rpod_mount_point="$1"
+rpod_mount_opts="$2"
+
+    if ! mount -o remount,"$rpod_mount_opts" "$rpod_mount_point"; then
+        printf "Failed to remount partition at mount point %s with mount options %s" "$rpod_mount_opts" "$rpod_mount_point"
+        exit 65
+    fi
+}
